#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --output HDMI-0 --mode 2560x1440 --rotate left --left-of DP-2
bspc monitor HDMI-0 I
bspc monitor DP-2 -d II III IV V VI

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a xfce4-terminal desktop='^3'
spc rule -a Google-chrome desktop='^4'
bspc rule -a spotify desktop='^6'
#bspc rule -a Whatsapp state=floating

xrdb ${HOME}/.Xresources
$HOME/.config/polybar/launch.sh --forest &
flameshot &
picom &
$HOME/.fehbg
