static const char black[]       = "#282828";
static const char white[]       = "#ebdbb2";
static const char gray2[]       = "#928374"; // unfocused window border
static const char gray3[]       = "#5d6061";
static const char gray4[]       = "#282b2c";
static const char blue[]        = "#83a598";  // focused window border
static const char green[]       = "#b8bb26";
static const char red[]         = "#fb4934";
static const char orange[]      = "#d6b676";
static const char yellow[]      = "#fabd2f";
static const char pink[]        = "#cc7f94";
static const char col_borderbar[]  = "#1e2122"; // inner border
