#! /bin/sh
#set keyboard settings
setxkbmap -layout us -variant intl

# set monitor settings
xrandr --output DP-4 --primary --mode 3440x1440 --rotate normal --output DVI-D-0 --mode 1600x900 --rotate left --left-of DP-4

bspc monitor DP-4 -d home www dev play chat
bspc monitor DVI-D-0 -d moni

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#set main border color
bspc config focused_border_color "#BF616A"
bspc config normal_border_color "#353b45"

#send to home desktop
bspc rule --add Pcmanfm                    desktop='home' follow=on
#send to www desktop
bspc rule --add firefox-esr                desktop='www' follow=on
#send to dev desktop
bspc rule --add St                         desktop='dev' follow=on
bspc rule --add gvim                       desktop='dev' follow=on
bspc rule --add code-oss                   desktop='dev' follow=on
#send to play desktop
bspc rule --add leagueclientux.exe         desktop='play' follow=on state=floating
bspc rule --add vlc                        desktop='play' follow=on
bspc rule --add Lutris                     desktop='play' follow=on
bspc rule --add steam                      desktop='play' --one-shot follow=on
#send to chat desktop

#send to moni desktop
bspc rule --add discord                    desktop='moni' follow=off
bspc rule --add Microsoft Teams - Preview  desktop='moni' follow=off
bspc rule --add Spotify                    desktop='moni' follow=off
# autostart up applications
~/.config/polybar/launch.sh &
picom &
feh --bg-fill ~/pictures/neon.png &
xrdb merge ~/.Xresources &
flameshot &
sxhkd
